- name: Startpage
  #width: slim
  hide-desktop-navigation: false
  center-vertically: false
  columns:
    - size: small
      widgets:
        - type: to-do
          hide-header: true
          #- type: calendar
          #first-day-of-week: monday

        - type: custom-api
          title: 今日黄历
          hide-header: true
          cache: 12h
          url: "https://api.52vmy.cn/api/wl/wnl/huangli"
          template: |
            <div style="font-family: sans-serif; line-height: 1.5; padding: 10px;">
              <!-- 日期 -->
              <h2 style="text-align: center; margin-bottom: 5px; color: #d35400;">{{ .JSON.String "data.date" }}</h2>
              <p style="text-align: center; margin-bottom: 15px; color: #7f8c8d;"><strong>农历：</strong>{{ .JSON.String "data.lunar" }}</p>
        
              <!-- 宜 -->
              <div>
                <h4 style="margin-bottom: 5px; color: #27ae60;">宜：</h4>
                <span style="background-color: #27ae60; color: #fff; padding: 4px 8px; border-radius: 4px; font-size: 0.85em;">
                  {{ range .JSON.Array "data.info" }}
                    {{ if eq (.String "name") "吉神宜趋" }}
                      {{ .String "index" }}
                    {{ end }}
                  {{ end }}
                </span>
              </div>
        
              <!-- 忌 -->
              <div style="margin-top: 10px;">
                <h4 style="margin-bottom: 5px; color: #c0392b;">忌：</h4>
                <span style="background-color: #c0392b; color: #fff; padding: 4px 8px; border-radius: 4px; font-size: 0.85em;">
                  {{ range .JSON.Array "data.info" }}
                    {{ if eq (.String "name") "凶神宜忌" }}
                      {{ .String "index" }}
                    {{ end }}
                  {{ end }}
                </span>
              </div>
            </div>

        - type: custom-api
          hide-header: true
          title: LeetCode Daily Question
          cache: 12h
          url: https://leetcode.com/graphql
          method: POST
          headers:
            Accept: application/json
          body-type: json
          body:
            query: |
              query questionOfToday {
                activeDailyCodingChallengeQuestion {
                  link
                  question {
                    questionId
                    title
                    difficulty
                    topicTags {
                      name
                      slug
                    }
                  }
                }
              }
            operationName: questionOfToday
          template: |
            <div class="leetcode-card">
              <style>
                .leetcode-card {
                  max-width: 600px;
                  margin: 8px auto;
                  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                  transition: transform 0.2s ease, box-shadow 0.2s ease;
                }
                .leetcode-card h1 {
                  font-size: 24px;
                  margin: 0 0 16px;
                  line-height: 1.3;
                }
                .leetcode-card h1 a {
                  color: #8CAAEE;
                  text-decoration: none;
                  transition: color 0.2s ease;
                }
                .leetcode-card h1 a:hover {
                  color: #BAC8FF;
                  text-decoration: underline;
                }
                .leetcode-card p {
                  margin: 8px 0;
                  color: #C6D0F5;
                  font-size: 16px;
                }
                .leetcode-card .difficulty {
                  font-weight: 600;
                  color: #A5ADCE;
                }
                .leetcode-card .difficulty.Easy {
                  color: #A6D189;
                }
                .leetcode-card .difficulty.Medium {
                  color: #E5C890;
                }
                .leetcode-card .difficulty.Hard {
                  color: #E78284;
                }
                .leetcode-card .topics {
                  display: flex;
                  flex-wrap: wrap;
                  gap: 8px;
                  margin: 12px 0;
                }
                .leetcode-card .topic-tag {
                  background: #CA9EE6;
                  color: #303446;
                  padding: 4px 12px;
                  border-radius: 16px;
                  font-size: 14px;
                  font-weight: 500;
                  transition: transform 0.2s ease;
                }
                .leetcode-card .topic-tag:hover {
                  transform: scale(1.05);
                }
                .leetcode-card .premium {
                  color: #E78284;
                  font-weight: 600;
                  margin-top: 12px;
                }
                @media (max-width: 600px) {
                  .leetcode-card {
                    padding: 16px;
                    margin: 8px;
                  }
                  .leetcode-card h1 {
                    font-size: 20px;
                  }
                  .leetcode-card p {
                    font-size: 14px;
                  }
                  .leetcode-card .topic-tag {
                    font-size: 12px;
                    padding: 3px 10px;
                  }
                }
              </style>
              <h1>
                <a href="https://leetcode.com{{ .JSON.String "data.activeDailyCodingChallengeQuestion.link" }}" target="_blank">
                  {{ .JSON.String "data.activeDailyCodingChallengeQuestion.question.questionId" }} - {{ .JSON.String "data.activeDailyCodingChallengeQuestion.question.title" }}
                </a>
              </h1>
              <p class="difficulty {{ .JSON.String "data.activeDailyCodingChallengeQuestion.question.difficulty" }}"><strong>Difficulty:</strong> {{ .JSON.String "data.activeDailyCodingChallengeQuestion.question.difficulty" }}</p>
              <p><strong>Topics:</strong></p>
              <div class="topics">
                {{ if .JSON.Exists "data.activeDailyCodingChallengeQuestion.question.topicTags" }}
                  {{ range .JSON.Array "data.activeDailyCodingChallengeQuestion.question.topicTags" }}
                    <span class="topic-tag">{{ .String "name" }}</span>
                  {{ end }}
                {{ else }}
                  <span class="topic-tag">None</span>
                {{ end }}
              </div>
              {{ if .JSON.Bool "data.activeDailyCodingChallengeQuestion.question.paidOnly" }}
                <p class="premium">This is a Premium question</p>
              {{ end }}
            </div>

    - size: full
      widgets:
        - type: search
          hide-header: true
          #autofocus: true
          search-engine: google

        - type: bookmarks
          hide-header: true
          groups:
            - title: Virtaitech
              hide-arrow: true
              links:
                - title: zentao
                  url: http://zentao.virtaitech.com/my/
                  icon: mdi:bug
                - title: confluence
                  url: http://confluence.virtaitech.com/
                  icon: si:confluence
                - title: Office 365
                  url: https://microsoft365.microsoftonline.cn/?auth=2
                  icon: mdi:microsoft-office
                - title: Outlook
                  url: https://partner.outlook.cn/mail/
                  icon: mdi:microsoft-outlook
                - title: 一心向上
                  url: https://esop.uponeshare.com/staff/home
                  icon: si:figshare
            - title: Tools
              hide-arrow: true
              links:
                - title: 网站导航
                  url: http://121.199.11.62:8080/
                  icon: mdi:account
                - title: Chatgpt
                  url: https://chatgpt.com/
                  icon: si:chatbot
                - title: Github
                  url: https://github.com/yao-ge
                  icon: si:github
                - title: 量化
                  url: http://121.199.11.62:5700/query
                  icon: si:qwant
                - title: 阿里云盘
                  url: http://121.199.11.62:8002/login
                  icon: si:googlecloudstorage
                - title: Notion
                  url: https://www.notion.so/2025-167c4cded91280aeb5fdd723b48a617c
                  icon: si:notion
                - title: Frps dashboard
                  url: http://121.199.11.62:5000/
                  icon: mdi:monitor-dashboard
                - title: Westdata
                  url: https://wd-gold.com/clientarea.php
                  icon: si:envoyproxy
                - title: blog
                  url: https://yao-ge.github.io/
                  icon: si:blogger
                - title: Base64
                  url: https://base64.us/
                  icon: si:xcode
                - title: Json manager
                  url: http://121.199.11.62:8080/json-manager
                  icon: si:json
            - title: Knowledges
              hide-arrow: true
              links:
                - title: Folo
                  url: https://app.follow.is/timeline/view-0/all/pending
                  icon: si:folo
                - title: Zhihu
                  url: https://www.zhihu.com/signin?next=%2F
                  icon: si:zhihu
                - title: 小林coding
                  url: https://xiaolincoding.com/
                  icon: si:coder
                - title: Leetcode
                  url: https://leetcode.cn/
                  icon: si:leetcode
            - title: Entertainment
              hide-arrow: true
              links:
                - title: YouTube
                  url: https://www.youtube.com/
                  icon: si:youtube
                - title: Prime Video
                  url: https://www.primevideo.com/
                  icon: si:airplayvideo
                - title: Disney+
                  url: https://www.disneyplus.com/
                  icon: mdi:animation-play
            - title: Social
              hide-arrow: true
              links:
                - title: Reddit
                  url: https://www.reddit.com/
                  icon: si:reddit
                - title: Twitter
                  url: https://twitter.com/
                  icon: si:x
                - title: Instagram
                  url: https://www.instagram.com/
                  icon: si:instagram

    - size: small
      widgets:
        - type: weather
          hide-header: true
          location: Shanghai, China 
          units: metric # alternatively "imperial"
          hour-format: 24h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          hide-location: true

        - type: markets
          hide-header: true
          cache: 5s 
          markets:
            #- symbol: SPY
            #  name: S&P 500
            - symbol: BTC-USD
              name: Bitcoin
              chart-link: https://www.tradingview.com/chart/?symbol=INDEX:BTCUSD
            - symbol: ETH-USD
              name: Eth 
            - symbol: DOGE-USD
              name: Doge 
            - symbol: NDX
              name: NSDK
            - symbol: NVDA
              name: NVIDIA

          #- type: releases
          #cache: 1d
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          # token: ...
          #repositories:
          #  - glanceapp/glance
          #  - go-gitea/gitea
          #  - immich-app/immich
          #  - syncthing/syncthing
        - type: server-stats
          hide-header: true
          servers:
            - type: local
              name: Services

        - type: docker-containers
          hide-header: true
