- name: Subscription
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  hide-desktop-navigation: false
  columns:
    - size: small
      widgets:
        - type: twitch-channels
          channels:
            - theprimeagen
            - j_blow
            - giantwaffle
            - cohhcarnage
            - christitustech
            - EJ_SA

    - size: full
      widgets:
        - type: group
          widgets:
            - type: rss
              limit: 1000
              collapse-after: 3
              cache: 1h
              style: vertical-list
              feeds:
                - url: https://rss.app/feeds/2RtPJjH0eakHpOX9.xml
                  title: Fan Donald J. Trump Posts From Truth Social


        - type: videos
          channels:
            - UCrCWHtK87Qe7oYjbaYQd9bQ
            - UC9v3JGut2Z1PxrXEpGzgEAA

        - type: split-column
          max-columns: 3
          widgets:
            - type: reddit
              subreddit: news
              show-thumbnails: true
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true
